name: First Workflow
on: workflow_dispatch

jobs:
  first_job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done bye!"
