name: Run tests on local runner
on:
#  push:
#    branches:
#      - main
#  schedule:
#    - cron: "22 22 * * *"
  workflow_dispatch:

jobs:
  test_job:
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
    - name: Download repository
      uses: actions/checkout@v3

    - name: Run tests on push
      run: ./gradlew clean executeFeatures -PcucumberOptions="--tags @Boards"

    - name: Add Index file for report deploy
      run:
        Rename-Item -Path "F:/actions-runner/_work/web-automation-demo/web-automation-demo/build/cucumber/reports/cucumber-html-reports/overview-features.html" -NewName "index.html"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: reg-results
        path: build/cucumber/reports

    - name: Deploy report page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/cucumber/reports/cucumber-html-reports
