name: Run test on push
on:
  push:
    branches: "main"
jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
    - name: Download repository
      uses: actions/checkout@v3

    - name: Set Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 11
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Install chrome
#      uses: browser-actions/setup-chrome@v1
      run: |
        set -ex
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run tests on push
      run: ./gradlew clean executeFeatures -PcucumberOptions="--tags @Boards"

    - name: Deploy report page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/cucumber/reports/cucumber-html-reports
